version: "3"
services:
  springbootdocker:
    image: dinhluong16101999/springbootdocker
    ports:
      - "80:8080"
      
  webcallapi:
    image: dinhluong16101999/webcallapi
    ports: 
      - "5000:80"
    depends_on:
      - springbootdocker
            